language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "PyUnit Tests"            # names the first Tests stage job
      script:
        - pytest
    - stage: Build
      name: "Build Docker Image"
      services:
        - docker
      script:
        - docker build -t abhijithvg/pythondemo:travisci .
    - stage: deploy
      name: "Push Docker Image to Dockerhub"
      deploy:
        provider: script
        script: bash docker_push
        on:
          branch: master
