language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "PyUnit Tests"            # names the first Tests stage job
      script:
        - pytest
    # - stage: Build
    #   name: "Build Docker Image"
    #   services:
    #     - docker
    #   script:
    #     - docker build -t abhijithvg/pythondemo:travisci .
    - stage: build n push
      name: "Build and Push Docker Image to Dockerhub"
      services:
        - docker
      script:
        # - docker build -t abhijithvg/pythondemo:travisci .
        - bash docker_buildnpush
    # - stage: Test Image
    #   script:
    #     - docker run --rm $DOCKER_USERNAME/pythondemo:latest cat app.py
